#!/usr/bin/env python3
"""
Karen AI - Model Export Script

Exports a fine-tuned Karen AI model through the following pipeline:
  1. Merge LoRA adapter weights with the base model
  2. Save the merged model in safetensors format
  3. Convert to GGUF format via llama.cpp (with quantisation)
  4. Generate an Ollama Modelfile
  5. Optionally import into Ollama via ``ollama create``

Usage:
    python export_model.py --adapter-path ./output/karen-adapter --base-model meta-llama/Llama-3.2-1B
    python export_model.py --adapter-path ./output/karen-adapter --output-dir ./export --quantization Q5_K_M
    python export_model.py --adapter-path ./output/karen-adapter --ollama-import
"""

from __future__ import annotations

import argparse
import json
import logging
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Optional

import torch
from colorama import Fore, Style, init as colorama_init
from transformers import AutoModelForCausalLM, AutoTokenizer

# Initialise colorama for cross-platform colour support
colorama_init(autoreset=True)

# ---------------------------------------------------------------------------
# Attempt to import project config; fall back to sensible defaults
# ---------------------------------------------------------------------------
try:
    from karen_config import (  # type: ignore[import-untyped]
        BASE_MODEL,
        SYSTEM_PROMPT,
        MODEL_NAME,
    )
except ImportError:
    BASE_MODEL = "meta-llama/Llama-3.2-1B"
    SYSTEM_PROMPT = (
        "You are Karen, a warm and supportive AI companion for children "
        "aged 6-12. You help kids navigate emotions, friendships, and "
        "growing up with age-appropriate guidance."
    )
    MODEL_NAME = "karen-ai"

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Quantisation presets
# ---------------------------------------------------------------------------
QUANTIZATION_CHOICES: list[str] = ["Q4_0", "Q4_K_M", "Q5_K_M", "Q8_0", "F16"]

# ---------------------------------------------------------------------------
# Ollama Modelfile template
# ---------------------------------------------------------------------------
MODELFILE_TEMPLATE = """# Karen AI - Ollama Modelfile
# Generated by Karen AI Export Pipeline

FROM {gguf_path}

SYSTEM \"\"\"{system_prompt}\"\"\"

TEMPLATE \"\"\"{{{{- if .System }}}}
<|start_header_id|>system<|end_header_id|>

{{{{ .System }}}}<|eot_id|>
{{{{- end }}}}
{{{{- range .Messages }}}}
<|start_header_id|>{{{{ .Role }}}}<|end_header_id|>

{{{{ .Content }}}}<|eot_id|>
{{{{- end }}}}
<|start_header_id|>assistant<|end_header_id|>

\"\"\"

# Optimal parameters for Karen AI
PARAMETER temperature 0.7
PARAMETER top_p 0.9
PARAMETER top_k 40
PARAMETER repeat_penalty 1.1
PARAMETER num_ctx 2048
PARAMETER stop "<|eot_id|>"
PARAMETER stop "<|end_of_text|>"
"""


# ---------------------------------------------------------------------------
# Step helpers
# ---------------------------------------------------------------------------
class ExportStage:
    """Context manager for stage-level logging with colour output."""

    def __init__(self, step_num: int, total_steps: int, description: str) -> None:
        self.step_num = step_num
        self.total_steps = total_steps
        self.description = description
        self.start_time: float = 0.0

    def __enter__(self) -> "ExportStage":
        self.start_time = time.perf_counter()
        print(
            f"\n{Fore.YELLOW}[{self.step_num}/{self.total_steps}] "
            f"{self.description}...{Style.RESET_ALL}"
        )
        logger.info("Starting: %s", self.description)
        return self

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        elapsed = time.perf_counter() - self.start_time
        if exc_type is None:
            print(
                f"  {Fore.GREEN}✓ {self.description} completed "
                f"({elapsed:.1f}s){Style.RESET_ALL}"
            )
            logger.info("Completed: %s (%.1fs)", self.description, elapsed)
        else:
            print(
                f"  {Fore.RED}✗ {self.description} failed: "
                f"{exc_val}{Style.RESET_ALL}"
            )
            logger.error("Failed: %s — %s", self.description, exc_val)


# ---------------------------------------------------------------------------
# Step 1: Merge LoRA adapter
# ---------------------------------------------------------------------------
def merge_adapter(
    adapter_path: str,
    base_model: str,
) -> tuple[AutoModelForCausalLM, AutoTokenizer]:
    """Load the base model and merge LoRA adapter weights.

    Args:
        adapter_path: Path to the LoRA adapter directory.
        base_model: HuggingFace model ID or local path for the base model.

    Returns:
        Tuple of (merged_model, tokenizer).

    Raises:
        FileNotFoundError: If the adapter path does not exist.
        RuntimeError: If merging fails.
    """
    from peft import PeftModel  # type: ignore[import-untyped]

    adapter_dir = Path(adapter_path)
    if not adapter_dir.exists():
        raise FileNotFoundError(f"Adapter path does not exist: {adapter_dir}")

    if not (adapter_dir / "adapter_config.json").exists():
        raise FileNotFoundError(
            f"No adapter_config.json found in {adapter_dir}. "
            "Is this a valid LoRA adapter directory?"
        )

    logger.info("Loading base model: %s", base_model)
    print(f"  Loading base model: {Fore.CYAN}{base_model}{Style.RESET_ALL}")

    base = AutoModelForCausalLM.from_pretrained(
        base_model,
        torch_dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True,
    )

    logger.info("Applying LoRA adapter from: %s", adapter_path)
    print(f"  Applying adapter: {Fore.CYAN}{adapter_path}{Style.RESET_ALL}")

    model = PeftModel.from_pretrained(base, adapter_path)

    logger.info("Merging adapter weights with base model")
    print(f"  Merging weights...")

    merged_model = model.merge_and_unload()

    tokenizer = AutoTokenizer.from_pretrained(
        base_model,
        trust_remote_code=True,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    logger.info("Adapter merged successfully")
    return merged_model, tokenizer


# ---------------------------------------------------------------------------
# Step 2: Save merged model
# ---------------------------------------------------------------------------
def save_merged_model(
    model: AutoModelForCausalLM,
    tokenizer: AutoTokenizer,
    output_dir: Path,
) -> Path:
    """Save the merged model in safetensors format.

    Args:
        model: The merged model.
        tokenizer: The corresponding tokenizer.
        output_dir: Root output directory.

    Returns:
        Path to the saved model directory.
    """
    merged_dir = output_dir / "merged_model"
    merged_dir.mkdir(parents=True, exist_ok=True)

    logger.info("Saving merged model to: %s", merged_dir)
    print(f"  Output directory: {Fore.CYAN}{merged_dir}{Style.RESET_ALL}")

    model.save_pretrained(
        merged_dir,
        safe_serialization=True,  # Use safetensors format
    )
    tokenizer.save_pretrained(merged_dir)

    # Calculate and report saved size
    total_size = sum(f.stat().st_size for f in merged_dir.rglob("*") if f.is_file())
    size_gb = total_size / (1024 ** 3)
    print(f"  Model size: {Fore.CYAN}{size_gb:.2f} GB{Style.RESET_ALL}")

    logger.info("Merged model saved (%.2f GB)", size_gb)
    return merged_dir


# ---------------------------------------------------------------------------
# Step 3: Convert to GGUF
# ---------------------------------------------------------------------------
def find_convert_script(llama_cpp_path: Optional[str]) -> Optional[Path]:
    """Locate the convert_hf_to_gguf.py script in llama.cpp.

    Args:
        llama_cpp_path: Explicit path to the llama.cpp directory, or None.

    Returns:
        Path to the conversion script, or None if not found.
    """
    candidates: list[Path] = []

    if llama_cpp_path:
        candidates.append(Path(llama_cpp_path) / "convert_hf_to_gguf.py")

    # Common locations
    candidates.extend([
        Path("llama.cpp") / "convert_hf_to_gguf.py",
        Path.home() / "llama.cpp" / "convert_hf_to_gguf.py",
        Path("/opt/llama.cpp") / "convert_hf_to_gguf.py",
    ])

    for candidate in candidates:
        if candidate.exists():
            return candidate

    return None


def convert_to_gguf(
    merged_model_dir: Path,
    output_dir: Path,
    quantization: str,
    model_name: str,
    llama_cpp_path: Optional[str] = None,
) -> Optional[Path]:
    """Convert the merged HuggingFace model to GGUF format.

    Uses llama.cpp's ``convert_hf_to_gguf.py`` script. If llama.cpp is not
    found, the step is skipped with a warning.

    Args:
        merged_model_dir: Path to the merged HF model directory.
        output_dir: Root output directory.
        quantization: Quantisation level (e.g. Q4_K_M).
        model_name: Name for the output GGUF file.
        llama_cpp_path: Optional explicit path to llama.cpp directory.

    Returns:
        Path to the GGUF file, or None if conversion was skipped.
    """
    convert_script = find_convert_script(llama_cpp_path)

    if convert_script is None:
        logger.warning(
            "llama.cpp not found. GGUF conversion skipped. "
            "Install llama.cpp and provide --llama-cpp-path, or clone it to "
            "a standard location."
        )
        print(
            f"  {Fore.YELLOW}⚠ llama.cpp not found — GGUF conversion skipped{Style.RESET_ALL}"
        )
        print(
            f"  {Fore.YELLOW}  Install: git clone https://github.com/ggerganov/llama.cpp{Style.RESET_ALL}"
        )
        print(
            f"  {Fore.YELLOW}  Then re-run with --llama-cpp-path /path/to/llama.cpp{Style.RESET_ALL}"
        )
        return None

    gguf_dir = output_dir / "gguf"
    gguf_dir.mkdir(parents=True, exist_ok=True)

    # First convert to f16 GGUF
    f16_path = gguf_dir / f"{model_name}-f16.gguf"
    gguf_path = gguf_dir / f"{model_name}-{quantization}.gguf"

    logger.info("Converting to GGUF with %s quantisation", quantization)
    print(f"  Convert script: {Fore.CYAN}{convert_script}{Style.RESET_ALL}")
    print(f"  Quantisation:   {Fore.CYAN}{quantization}{Style.RESET_ALL}")

    # Step 3a: Convert HF model to F16 GGUF
    print(f"  Converting HF → GGUF (F16)...")
    convert_cmd = [
        sys.executable,
        str(convert_script),
        str(merged_model_dir),
        "--outfile", str(f16_path),
        "--outtype", "f16",
    ]

    try:
        result = subprocess.run(
            convert_cmd,
            capture_output=True,
            text=True,
            timeout=1800,  # 30 minute timeout
        )
        if result.returncode != 0:
            logger.error("GGUF conversion failed:\n%s", result.stderr)
            print(f"  {Fore.RED}✗ Conversion failed: {result.stderr[:200]}{Style.RESET_ALL}")
            return None
    except subprocess.TimeoutExpired:
        logger.error("GGUF conversion timed out after 30 minutes")
        print(f"  {Fore.RED}✗ Conversion timed out{Style.RESET_ALL}")
        return None
    except FileNotFoundError as exc:
        logger.error("Failed to run conversion script: %s", exc)
        print(f"  {Fore.RED}✗ Could not execute conversion script: {exc}{Style.RESET_ALL}")
        return None

    # Step 3b: Quantise if not F16
    if quantization != "F16":
        print(f"  Quantising F16 → {quantization}...")

        # Look for llama-quantize binary
        llama_cpp_dir = convert_script.parent
        quantize_bin = None
        for name in ["llama-quantize", "quantize"]:
            for subdir in [llama_cpp_dir, llama_cpp_dir / "build" / "bin"]:
                candidate = subdir / name
                # Check with and without .exe on Windows
                for ext in ["", ".exe"]:
                    full = candidate.with_suffix(ext) if ext else candidate
                    if full.exists():
                        quantize_bin = full
                        break
                if quantize_bin:
                    break
            if quantize_bin:
                break

        if quantize_bin is None:
            logger.warning(
                "llama-quantize binary not found. Keeping F16 format. "
                "Build llama.cpp to enable quantisation."
            )
            print(
                f"  {Fore.YELLOW}⚠ Quantize binary not found — "
                f"keeping F16 format{Style.RESET_ALL}"
            )
            # Rename f16 to final path
            f16_path.rename(gguf_path.with_name(f"{model_name}-F16.gguf"))
            gguf_path = gguf_path.with_name(f"{model_name}-F16.gguf")
        else:
            quantize_cmd = [
                str(quantize_bin),
                str(f16_path),
                str(gguf_path),
                quantization,
            ]
            try:
                result = subprocess.run(
                    quantize_cmd,
                    capture_output=True,
                    text=True,
                    timeout=1800,
                )
                if result.returncode != 0:
                    logger.error("Quantisation failed:\n%s", result.stderr)
                    print(
                        f"  {Fore.RED}✗ Quantisation failed: "
                        f"{result.stderr[:200]}{Style.RESET_ALL}"
                    )
                    return f16_path  # Return f16 as fallback
                # Clean up f16 intermediate file
                if f16_path.exists() and gguf_path.exists():
                    f16_path.unlink()
                    logger.info("Removed intermediate F16 file")
            except subprocess.TimeoutExpired:
                logger.error("Quantisation timed out")
                print(f"  {Fore.RED}✗ Quantisation timed out{Style.RESET_ALL}")
                return f16_path
    else:
        gguf_path = f16_path

    if gguf_path.exists():
        size_gb = gguf_path.stat().st_size / (1024 ** 3)
        print(f"  GGUF size: {Fore.CYAN}{size_gb:.2f} GB{Style.RESET_ALL}")
        logger.info("GGUF file created: %s (%.2f GB)", gguf_path, size_gb)

    return gguf_path


# ---------------------------------------------------------------------------
# Step 4: Create Modelfile
# ---------------------------------------------------------------------------
def create_modelfile(
    gguf_path: Optional[Path],
    output_dir: Path,
    model_name: str,
) -> Path:
    """Generate an Ollama Modelfile.

    Args:
        gguf_path: Path to the GGUF model file (or None if unavailable).
        output_dir: Root output directory.
        model_name: Model name for the Modelfile.

    Returns:
        Path to the generated Modelfile.
    """
    modelfile_path = output_dir / "Modelfile"

    gguf_ref = str(gguf_path) if gguf_path else f"./{model_name}.gguf"

    content = MODELFILE_TEMPLATE.format(
        gguf_path=gguf_ref,
        system_prompt=SYSTEM_PROMPT,
    )

    modelfile_path.write_text(content, encoding="utf-8")
    logger.info("Modelfile created: %s", modelfile_path)
    print(f"  Modelfile: {Fore.CYAN}{modelfile_path}{Style.RESET_ALL}")

    return modelfile_path


# ---------------------------------------------------------------------------
# Step 5: Ollama import
# ---------------------------------------------------------------------------
def import_to_ollama(
    modelfile_path: Path,
    model_name: str,
) -> bool:
    """Import the model into Ollama using ``ollama create``.

    Args:
        modelfile_path: Path to the Modelfile.
        model_name: Name for the Ollama model.

    Returns:
        True if import succeeded, False otherwise.
    """
    # Check if ollama is available
    ollama_bin = shutil.which("ollama")
    if ollama_bin is None:
        logger.warning("Ollama not found in PATH. Skipping import.")
        print(
            f"  {Fore.YELLOW}⚠ Ollama not found in PATH — "
            f"skipping import{Style.RESET_ALL}"
        )
        print(
            f"  {Fore.YELLOW}  Install Ollama: https://ollama.com/download{Style.RESET_ALL}"
        )
        print(
            f"  {Fore.YELLOW}  Then run: ollama create {model_name} "
            f"-f {modelfile_path}{Style.RESET_ALL}"
        )
        return False

    print(f"  Running: {Fore.CYAN}ollama create {model_name} -f {modelfile_path}{Style.RESET_ALL}")

    try:
        result = subprocess.run(
            ["ollama", "create", model_name, "-f", str(modelfile_path)],
            capture_output=True,
            text=True,
            timeout=600,  # 10 minute timeout
        )
        if result.returncode == 0:
            logger.info("Model imported to Ollama as '%s'", model_name)
            print(f"  {Fore.GREEN}✓ Model available as: ollama run {model_name}{Style.RESET_ALL}")
            return True
        else:
            logger.error("Ollama import failed:\n%s", result.stderr)
            print(f"  {Fore.RED}✗ Import failed: {result.stderr[:200]}{Style.RESET_ALL}")
            return False
    except subprocess.TimeoutExpired:
        logger.error("Ollama import timed out after 10 minutes")
        print(f"  {Fore.RED}✗ Import timed out{Style.RESET_ALL}")
        return False
    except Exception as exc:
        logger.error("Ollama import error: %s", exc)
        print(f"  {Fore.RED}✗ Import error: {exc}{Style.RESET_ALL}")
        return False


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
def print_summary(
    output_dir: Path,
    model_name: str,
    gguf_path: Optional[Path],
    modelfile_path: Path,
    ollama_imported: bool,
) -> None:
    """Print a final summary of all exported artifacts.

    Args:
        output_dir: Root output directory.
        model_name: Model name.
        gguf_path: Path to the GGUF file (or None).
        modelfile_path: Path to the Modelfile.
        ollama_imported: Whether Ollama import was successful.
    """
    print(f"\n{Fore.CYAN}{'=' * 60}{Style.RESET_ALL}")
    print(f"{Fore.CYAN}  📦 Export Summary{Style.RESET_ALL}")
    print(f"{Fore.CYAN}{'=' * 60}{Style.RESET_ALL}")
    print(f"  Output directory: {output_dir}")
    print(f"  Merged model:     {output_dir / 'merged_model'}")

    if gguf_path and gguf_path.exists():
        print(f"  GGUF model:       {gguf_path}")
    else:
        print(f"  GGUF model:       {Fore.YELLOW}Not created{Style.RESET_ALL}")

    print(f"  Modelfile:        {modelfile_path}")

    if ollama_imported:
        print(f"  Ollama:           {Fore.GREEN}✓ Imported as '{model_name}'{Style.RESET_ALL}")
    else:
        print(f"  Ollama:           {Fore.YELLOW}Not imported{Style.RESET_ALL}")

    print(f"\n  {Fore.CYAN}Next steps:{Style.RESET_ALL}")
    if not ollama_imported:
        print(f"    1. Install Ollama: https://ollama.com/download")
        print(f"    2. Import model:   ollama create {model_name} -f {modelfile_path}")
        print(f"    3. Run model:      ollama run {model_name}")
    else:
        print(f"    Run model: ollama run {model_name}")

    print(f"\n{Fore.CYAN}{'=' * 60}{Style.RESET_ALL}\n")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    """Parse command-line arguments.

    Returns:
        Parsed arguments namespace.
    """
    parser = argparse.ArgumentParser(
        description="Karen AI — Model Export Pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python export_model.py --adapter-path ./output/karen-adapter\n"
            "  python export_model.py --adapter-path ./output/karen-adapter "
            "--quantization Q5_K_M --ollama-import\n"
        ),
    )
    parser.add_argument(
        "--adapter-path", required=True,
        help="Path to the LoRA adapter directory.",
    )
    parser.add_argument(
        "--base-model", default=BASE_MODEL,
        help=f"Base model HuggingFace ID or local path (default: {BASE_MODEL}).",
    )
    parser.add_argument(
        "--output-dir", default="export/",
        help="Output directory for exported artifacts (default: export/).",
    )
    parser.add_argument(
        "--quantization", default="Q4_K_M", choices=QUANTIZATION_CHOICES,
        help="GGUF quantisation level (default: Q4_K_M).",
    )
    parser.add_argument(
        "--model-name", default="karen-ai",
        help="Name for the exported model (default: karen-ai).",
    )
    parser.add_argument(
        "--ollama-import", action="store_true",
        help="Automatically import the model into Ollama after export.",
    )
    parser.add_argument(
        "--llama-cpp-path", default=None,
        help="Path to the llama.cpp directory (for GGUF conversion).",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    """Run the full model export pipeline."""
    args = parse_args()
    output_dir = Path(args.output_dir)
    total_steps = 5 if args.ollama_import else 4

    print(f"\n{Fore.CYAN}{'=' * 60}{Style.RESET_ALL}")
    print(f"{Fore.CYAN}  🧸 Karen AI — Model Export Pipeline{Style.RESET_ALL}")
    print(f"{Fore.CYAN}{'=' * 60}{Style.RESET_ALL}")
    print(f"  Adapter:      {args.adapter_path}")
    print(f"  Base model:   {args.base_model}")
    print(f"  Output:       {output_dir}")
    print(f"  Quantisation: {args.quantization}")
    print(f"  Model name:   {args.model_name}")

    gguf_path: Optional[Path] = None
    ollama_imported = False

    # --- Step 1: Merge adapter ---
    with ExportStage(1, total_steps, "Merging LoRA adapter with base model"):
        merged_model, tokenizer = merge_adapter(args.adapter_path, args.base_model)

    # --- Step 2: Save merged model ---
    with ExportStage(2, total_steps, "Saving merged model (safetensors)"):
        merged_dir = save_merged_model(merged_model, tokenizer, output_dir)

    # Free memory after saving
    del merged_model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    logger.info("Freed GPU memory after saving merged model")

    # --- Step 3: Convert to GGUF ---
    with ExportStage(3, total_steps, f"Converting to GGUF ({args.quantization})"):
        gguf_path = convert_to_gguf(
            merged_dir, output_dir,
            args.quantization, args.model_name,
            args.llama_cpp_path,
        )

    # --- Step 4: Create Modelfile ---
    with ExportStage(4, total_steps, "Creating Ollama Modelfile"):
        modelfile_path = create_modelfile(gguf_path, output_dir, args.model_name)

    # --- Step 5: Ollama import (optional) ---
    if args.ollama_import:
        with ExportStage(5, total_steps, "Importing model to Ollama"):
            if gguf_path and gguf_path.exists():
                ollama_imported = import_to_ollama(modelfile_path, args.model_name)
            else:
                print(
                    f"  {Fore.YELLOW}⚠ No GGUF file available — "
                    f"skipping Ollama import{Style.RESET_ALL}"
                )
                logger.warning("Ollama import skipped: no GGUF file")

    # --- Summary ---
    print_summary(output_dir, args.model_name, gguf_path, modelfile_path, ollama_imported)

    print(f"{Fore.GREEN}  Export complete! 🎉{Style.RESET_ALL}\n")


if __name__ == "__main__":
    main()
